export default {
    SCREEN_MARGIN_HORIZONTAL: 24,
    LIST_ITEM_PADDING_VERTICAL: 12,
    LIST_ITEM_BORDER_WIDTH: 1,
    
    MARGIN_VERTICAL_SMALL: 8,
    MARGIN_VERTICAL_MEDIUM: 18,
    MARGIN_VERTICAL_BIG: 28,

    BUTTON_PADDING: 17,
    PADDING_SCROLLVIEW_BOTTOM: 32,

    BORDER_RADIUS_INPUT: 5,
    BORDER_RADIUS_TAG: 5,
    BORDER_RADIUS_PROGRESS: 5,
    BORDER_RADIUS_BUTTON: 8,
    BORDER_RADIUS_IMAGE: 12,
    BORDER_RADIUS_BAR: 28,

    TAG_FAT_PADDING_VERTICAL: 5,
    TAG_FAT_PADDING_HORIZONTAL: 10,
    TAG_MARGIN_END: 5,
    TAG_MARGIN_TOP: 4,

    PROGRESSBAR_HEIGHT: 10,
}