export default {
    SCREEN_MARGIN_HORIZONTAL: 24,
    LIST_ITEM_PADDING_VERTICAL: 12,
    LIST_ITEM_BORDER_WIDTH: 1,
    
    BORDER_RADIUS_INPUT: 5,
    BORDER_RADIUS_TAG: 5,
    BORDER_RADIUS_IMAGE: 12,
    BORDER_RADIUS_BAR: 28,
}